version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb2/:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=SCRUBBEDUSERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=SCRUBBEDPW
      - DOCKER_INFLUXDB_INIT_ORG=SCRUBBEDORG
      - DOCKER_INFLUXDB_INIT_BUCKET=SCRUBBEDBUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION=365d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=SCRUBBEDTOKEN
    ports:
      - "8086:8086"
